version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "backend:4"
        LoadBalancerInfo:
          ContainerName: "easymap-backend"
          ContainerPort: 8080
