spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${{secret.GOOGLE_CLIENT_ID}}
            client-secret: ${{secret.GOOGLE_CLIENT_SECRET}}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: profile, email
          kakao:
            client-id: ${{secret.KAKAO_CLIEND_ID}}
            client-secret: ${{secret.KAKAO_CLIENT_SECRET}}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    url: jdbc:postgresql://${{secret.DATASOURCE_URL}}
    driver-class-name: org.postgresql.Driver
    username: ${{secret.DB_USERNAME}}
    password: ${{secret.DB_PASSWORD}}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  redirect-url: ${{secret.REDIRECT_URL}}
  redirect-url-failed: ${{secret.REDIRECT_URL_FAILED}}


aws:
  s3:
    access-key: ${{secret.AWS_ACCESS_KEY}}
    secret-key: ${{secret.AWS_SECRET_ACCESS_KEY}}
    end-point: https://s3.ap-northeast-2.amazonaws.com
    region: ap-northeast-2
    bucket-name: ${{secret.AWS_IMAGE_BUCKET_NAME}}
    user-rawdata-bucket-name: ${{secret.AWS_USER_RAWDATA_BUCKET_NAME}}

apikey:
  vworld:
    conformKey: ${{secret.VWORLD_CONFORM_KEY}}
  juso:
    search:
      conformKey: ${{secret.JUSO_CONFORM_KEY}}